user  nginx;
worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # 기본 성능/로깅
  sendfile on;
  access_log    /var/log/nginx/access.log;
  error_log     /var/log/nginx/error.log;

  # conf.d 아래 서버 블록 분리 정의
  include /etc/nginx/conf.d/*.conf;
}
